//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tskmProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public File()
        {
            this.Tickets = new HashSet<Ticket>();
            this.Knowledgebases = new HashSet<Knowledgebase>();
        }
    
        public int fileID { get; set; }
        public string fileName { get; set; }
    
        public virtual ICollection<Ticket> Tickets { get; set; }
        public virtual ICollection<Knowledgebase> Knowledgebases { get; set; }
    }
}
