//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tskmProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KnowledgeComment
    {
        public int commentID { get; set; }
        public string commentDetail { get; set; }
        public string commentDate { get; set; }
        public int knowledgeID { get; set; }
        public int userID { get; set; }
    
        public virtual Knowledgebase Knowledgebase { get; set; }
        public virtual User User { get; set; }
    }
}
