//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tskmProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Knowledgebase
    {
        public Knowledgebase()
        {
            this.KnowledgeComment = new HashSet<KnowledgeComment>();
            this.Files = new HashSet<File>();
        }
    
        public int knowledgeID { get; set; }
        public string knowledgeTitle { get; set; }
        public string knowledgeDetail { get; set; }
        public System.DateTime knowledgeDate { get; set; }
        public int catagoryID { get; set; }
        public int userID { get; set; }
    
        public virtual Catagory Catagory { get; set; }
        public virtual ICollection<KnowledgeComment> KnowledgeComment { get; set; }
        public virtual ICollection<File> Files { get; set; }
        public virtual User User { get; set; }
    }
}
