//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tskmProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tskmContainer : DbContext
    {
        public tskmContainer()
            : base("name=tskmContainer")
        {
            this.Database.Connection.ConnectionString = "data source=TNASAN;initial catalog=tskmDB;user ID=sa;password=thA1g@m1ng;MultipleActiveResultSets=True;App=EntityFramework";
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<Catagory> Catagories { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Knowledgebase> Knowledgebases { get; set; }
        public virtual DbSet<TicketReply> TicketReplies { get; set; }
        public virtual DbSet<KnowledgeComment> KnowledgeComments { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<TicketHistory> TicketHistories { get; set; }
    }
}
