//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tskmProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.KnowledgeComment = new HashSet<KnowledgeComment>();
            this.Ticket = new HashSet<Ticket>();
            this.TicketReply = new HashSet<TicketReply>();
            this.Roles = new HashSet<Role>();
            this.Knowledgebases = new HashSet<Knowledgebase>();
        }
    
        public int userID { get; set; }
        public string userFname { get; set; }
        public string userLname { get; set; }
        public string userTel { get; set; }
        public string userEmail { get; set; }
        public string userPosition { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int departmentID { get; set; }
        public string userCode { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<KnowledgeComment> KnowledgeComment { get; set; }
        public virtual ICollection<Ticket> Ticket { get; set; }
        public virtual ICollection<TicketReply> TicketReply { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<Knowledgebase> Knowledgebases { get; set; }
    }
}
